### ISSUE TITLE
Sphere hanging when a certain monster hits a player

### ISSUE THREAD

**Issue by s0ckz** [Sphereserver/Scripts#10]
I was testing some monsters and found out the Dark Father (c_dark_father). When it hits a player, it simply hangs the Sphere...

There's an script error on the @Hit trigger. It's missing the ending DORAND statement.
I've also created an issue on Sphere because I think the interpreter should warn the programmer about the missing end statement: https://github.com/Sphereserver/Source/issues/90

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Scripts/commit/9f5a5e0536d8a98c916fca84338a4a10c9eb92ec
