### ISSUE TITLE
(sphere_system_treasure_maps.scp,54)Redefinition of resource with DEFNAME='i_ttm_l1'

### ISSUE THREAD

**Issue by azmanomer** [Sphereserver/Scripts#14]
There are also same itemdef at items/sphere_item_treasure_maps.scp

WARNING:(sphere_system_treasure_maps.scp,54)Redefinition of resource with DEFNAME='i_ttm_l1'
WARNING:(sphere_system_treasure_maps.scp,70)Redefinition of resource with DEFNAME='i_ttm_l2'
WARNING:(sphere_system_treasure_maps.scp,86)Redefinition of resource with DEFNAME='i_ttm_l3'
WARNING:(sphere_system_treasure_maps.scp,102)Redefinition of resource with DEFNAME='i_ttm_l4'
WARNING:(sphere_system_treasure_maps.scp,118)Redefinition of resource with DEFNAME='i_ttm_l5'
WARNING:(sphere_system_treasure_maps.scp,134)Redefinition of resource with DEFNAME='i_chest_treasure'

**Comment by coruja747** [comment]
are you using custom scripts? I checked here and it seems to be fine, these defnames are defined once and only on sphere_system_treasure_maps.scp

**Comment by azmanomer** [comment]
y i tought its orginal from here but it seems its not sorry my fault :)
