### ISSUE TITLE
sphere_monsters.scp

### ISSUE THREAD

**Issue by Hiroyito** [Sphereserver/Scripts#16]
On the "sphere_monsters.scp"

Layer "16652" in raptor def. there is the code couse problem. When you summon a raptor and going to its visual area, raptor starts to duplicate it self.

"ON=@NPCSeeNewPlayer
   //Summon pack
   IF (<FLAGS> & statf_conjured) || (<FLAGS> & statf_pet)
      RETURN 0
   ENDIF
   IF (<MANA> >= 25) && (<TAG0.CURFOLLOWER> < 2)
      MANA -= 25
      TAG0.CURFOLLOWER += 1
      SERV.NEWNPC c_raptor
      NEW.TAMING=0
      NEW.P=<P>
      NEW.HOME=<SRC.P>
      NEW.HOMEDIST=7
      NEW.ATTACK <SRC>
      NEW.f_NPCRemovalTimer 1200
   ENDIF
ON=@Death
   IF (<FINDID.i_summon_mem>)
      REF1=<FINDID.i_summon_mem.LINK.UID>
      IF (<REF1.ID>==c_raptor)
         REF1.TAG0.CURFOLLOWER -= 1
      ENDIF
   ENDIF"

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Scripts/commit/8d18f6221c12027a785dd797227ea71c1b806267
