### ISSUE TITLE
MISSING NAMES_DRAGON from sphere_name.scp

### ISSUE THREAD

**Issue by GitMadKing** [Sphereserver/Scripts#19]
[NAMES NAMES_DRAGON]
disapeared
but there are still chars using it
maybe was itended to remain just with type name like "ice dragon" but hasn't removed 
ON=@Create
   NAME=#NAMES_DRAGON

![image](https://user-images.githubusercontent.com/16067766/50576879-bbd95880-0e1b-11e9-8ebc-4534ffdbd7ea.png)

**Comment by coruja747** [comment]
most NPCs of sphere_monsters_custom.scp are custom NPCs probably made for an custom server, so you can safely remove these "NAME=#NAMES_DRAGON" lines (or the entire NPC) because these custom NPCs will be removed someday

**Comment by coruja747** [comment]
Fixed some months ago https://github.com/Sphereserver/Scripts/commit/13f50d13d7fd87de00d679a06bb59daf698bd9d1
