### ISSUE TITLE
New admin pannel SEARCh

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Scripts#21]
Seriously!  This new pannel is awsome! THX

Just a little bug on the arrow for next page in the search mode

LINE 101 on the script. But I don't know how fix it...

![image](https://user-images.githubusercontent.com/51728381/64048288-50c55a80-cb3f-11e9-81f7-fad2c0fb8467.png)

**Comment by coruja747** [comment]
Thanks for reporting 😃
I already fixed this, but since the script pack is only updated some few times to avoid excessive updates, I'm just waiting some few others updates to commit all files together. But anyway to fix this you just need to swap the dialog button 1 with button 2
```
ON=1   // <-- change this line to ON=2
...

ON=2   // <-- change this line to ON=1
...
```
