### ISSUE TITLE
New admin menu NOTE 

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Scripts#22]
When I add a note to a player, It's the player  showing at the beginning. I thought it was for the GM name.

![image](https://user-images.githubusercontent.com/51728381/64090711-92f6c380-cd1a-11e9-85ca-21f0bc3961af.png)

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Scripts/commit/8712426c6f99b890a829aaef6f7b314b0e118270
