### ISSUE TITLE
Hair Dye Dialog

### ISSUE THREAD

**Issue by Jhobean** [Sphereserver/Scripts#26]
I have a problem in dialog d_hair_dye

![image](https://user-images.githubusercontent.com/51728381/67613376-c6822700-f77a-11e9-8923-de8ae7487edd.png)

The problem seem to be in: 
sphere_dialog.scp

Any idea where the bug?

```
[DIALOG d_hair_dye]
50,50

page 0
resizepic 100 10 2600 350 355
resizepic 120 54 5100 110 270
dhtmlgump 70 25 400 35 0 0 <DEF.CENTER>Hair Color Selection Menu<DEF.CENTERE>
button 149 328 4005 4007 1 0 1
dhtmlgump 185 329 250 35 0 0 Dye my hair this color!

WHILE !(<isempty <DEF.Hair.Dye.<SRC.CTAG0.Hairstylist.Dye.Palette>.<eval <LOCAL._WHILE>+1>>>)
 ARGS=<DEF.Hair.Dye.<SRC.CTAG0.Hairstylist.Dye.Palette>.<eval <LOCAL._WHILE>+1>>
 dtext 130 <eval 59+(<LOCAL._WHILE>*22)> <eval <ARGV0>-1> *****
 button 207 <eval 60+(<LOCAL._WHILE>*22)> 5224 5224 0 <eval <LOCAL._WHILE>+1> 0
ENDWHILE

WHILE !(<isempty <DEF.Hair.Dye.<SRC.CTAG0.Hairstylist.Dye.Palette>.<eval <LOCAL._WHILE>+1>>>)
 ARGS=<DEF.Hair.Dye.<SRC.CTAG0.Hairstylist.Dye.Palette>.<eval <LOCAL._WHILE>+1>>
 page <eval <LOCAL._WHILE>+1>
 LOCAL.N=0
 FOR <ARGV0> <ARGV1>
  dtext <eval 278+((<LOCAL.N>/16)*80)> <eval 52+((<LOCAL.N>%16)*17)> <eval <LOCAL._FOR>-1> *****
  radio <eval 260+((<LOCAL.N>/16)*80)> <eval 52+((<LOCAL.N>%16)*17)> 210 211 0 <LOCAL._FOR>
  LOCAL.N ++
 ENDFOR
ENDWHILE
```

**Comment by coruja747** [comment]
This dialog is working fine, it require some CTAGs that are only set when it get opened through "d_hairstylist"

So to make it work correctly you must open d_hairstylist first (used by NPC c_hairstylist), or if you want call only d_hair_dye on an custom script you must set manually these CTAGs on the char before open the dialog

PS: note that <LOCAL._WHILE> counter is broken so the dialog will still not working, but I already fixed it on latest build, so you can keep using this same code and just update SphereSvr.exe

**Comment by Jhobean** [comment]
Thx again!!
