### ISSUE TITLE
Server name SphereServer 56d Nightly error

### ISSUE THREAD

**Issue by gmhao** [Sphereserver/Scripts#34]
Hello, I was old player on UO, and I am returning now, and I am trying to make I new UO server.
So I downloaded the sphereserver 56d nightly and All functions working fine, alright.
But when you change the name, in this line

[SERVERS]
MyShard
127.0.0.1
2593

in bottom,

for example

[SERVERS]
Prodigy Ultima Online
127.0.0.1
2593

The spheresrv just load and close
if I put

[SERVERS]
Prodigy
127.0.0.1
2593

just "Prodigy" the spheresrv loads and the game run normaly

So it this!!!! someone can help me??? It's issue or have to make something more???

Thanks a lot!!!!

**Comment by coruja747** [comment]
Fixed https://github.com/Sphereserver/Source/commit/7d4cd4793b7a89a42af22ca4f1505c8df4864674
Thanks for reporting, just update to latest nightly build, it should be working fine now
